### ISSUE TITLE
Request for 1.4.2

### ISSUE THREAD

**Issue by jbmikk** [SamWM/jquery-numeric#2]
I have a project which requires version 1.4.1 and I'm updating it to use npm.

The problem is I can't install 1.4.1 because it lacks a package.json file. Would it be possible for you to release a 1.4.2 version which is exactly like the 1.4.1 but including the package.json file?

I would like to update to the 1.5.0 version, but I don't know if it works with my project and I have a lot of libraries to move to my package.json and updating them all to newer versions is just too risky.

**Comment by SamWM** [comment]
I have added a package.json file, so it should be able to work via npm now

**Comment by anglepoised** [comment]
@SamWM I'm going through a similar process and - while I can see older versions have a `package.json`\- I'm not sure they've been published to npm. I think you need to use the `--tag` flag, per http://stackoverflow.com/a/27665031. Would you mind publishing `1.4.2`? It'd be very helpful.

**Comment by jbmikk** [comment]
You can install it directly from github like this:

```
npm install --save git+ssh://git@github.com:SamWM/jquery-numeric.git#v1.4.2
```

**Comment by anglepoised** [comment]
Thanks! That's what we're doing at the moment, but it'd be nice to point to an immutable package.
